name: Cypress e2e tests

on: 
	push:
		- main
	paths:
		- 'cypress/**.js'
		- 'cypress/**.json'
		- 'cypress/**.yml'

jobs:
	cypress:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout code
			  uses: actions/checkout@v4

			- name: Setup Node.js
			  uses: actions/setup-node@v4
			  with:
			  	node-version: 20.12.1
			
			- name Install dependencies
			  run: npm install
			  working directory: ./cypress